name: Trigger test run with Jest

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Jest
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Test with Jest       
        run: npm test
